" My vimrc

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-commentary'
Plugin 'thoughtbot/vim-rspec'
Plugin 'nanotech/jellybeans.vim'
Plugin 'vim-ruby/vim-ruby'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'garbas/vim-snipmate'
Plugin 'honza/vim-snippets'
Plugin 'scrooloose/nerdTree'
Plugin 'mileszs/ack.vim'
Plugin 'christoomey/vim-tmux-runner'
Plugin 'tpope/vim-dispatch'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ervandew/supertab'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'wesQ3/vim-windowswap'
call vundle#end()

filetype plugin indent on

let &t_Co=256
syntax enable

set background=dark
colorscheme jellybeans

let mapleader = "\<Space>"

set hidden
set autoread
set lazyredraw
set backspace=indent,eol,start
set history=1000
set scrolloff=4
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set secure
set autowrite
set number
set clipboard=unnamed

" Normal Mappings
nmap <leader>vr :sp $MYVIMRC<cr>
nmap <leader>so :source $MYVIMRC<cr>
nmap 0 ^

map <leader>vi :tabe $MYVIMRC<cr>
map <leader>tm :tabe ~/.tmux.conf<cr>

" Rspec.vim Mappings
let g:rspec_command = "Dispatch rspec {spec}"
map <leader>t :call RunCurrentSpecFile()<cr>
map <leader>s :call RunNearestSpec()<cr>
map <leader>l :call RunLastSpec()<cr>
map <leader>a :call RunAllSpecs()<cr>


let g:ctrlp_custom_ignore = {'dir': '\v[\/](.git)$'}
let g:ctrlp_prompt_mappings = { 
      \'AcceptSelection("e")': ['<2-LeftMouse>'],
      \'AcceptSelection("t")': ['<CR>'] 
      \}

let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files --others --cached --exclude-standard']

noremap <Leader>c <C-w>c
nnoremap \ :Ack --smart-case<SPACE>
nnoremap <leader>irb :VtrOpenRunner {'orientation':'h', 'percentage':50, 'cmd':'irb'}<cr>
nnoremap <leader>osr :VtrOpenRunner {'orientation':'h', 'percentage':50}<cr>

